name: Terraform CI

# Run the workflow on pull requests targeting the 'main' branch
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Fmt and Validate'
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout the code from the repository
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v2

      # Step 2: Set up Terraform CLI
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7  # You can set the version you want to use here

      # Step 3: Initialize Terraform
      - name: 'Terraform Init'
        run: terraform init

      # Step 4: Check Terraform formatting (recursively)
      - name: 'Terraform Fmt'
        run: terraform fmt -check -recursive

      # Step 5: Validate the Terraform configuration
      - name: 'Terraform Validate'
        run: terraform validate
